# Generated by Django 5.2.9 on 2025-12-11 04:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='encrypted_filename',
            field=models.CharField(blank=True, help_text='Encrypted filename for client-side encrypted files', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='storedfile',
            name='encryption_method',
            field=models.CharField(choices=[('none', 'No encryption'), ('server', 'Server-side encryption'), ('client', 'Client-side encryption')], default='none', help_text='Encryption method used for this file', max_length=20),
        ),
        migrations.AddField(
            model_name='storedfile',
            name='key_id',
            field=models.CharField(blank=True, help_text='Identifier for encryption key (for key rotation)', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='storedfile',
            index=models.Index(fields=['encryption_method'], name='storage_sto_encrypt_949213_idx'),
        ),
    ]
