# Generated by Django 6.0 on 2026-01-16 19:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_add_invite_tracking_fields"),
        ("storage", "0002_alter_storedfile_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileauditlog",
            name="justification",
            field=models.TextField(
                blank=True,
                help_text="Required justification for admin override access",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fileauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("list", "List directory"),
                    ("upload", "Upload file"),
                    ("download", "Download file"),
                    ("delete", "Delete file"),
                    ("move", "Move file"),
                    ("copy", "Copy file"),
                    ("edit", "Edit content"),
                    ("preview", "Preview content"),
                    ("create_dir", "Create directory"),
                    ("bulk_delete", "Bulk delete"),
                    ("bulk_move", "Bulk move"),
                    ("bulk_copy", "Bulk copy"),
                    ("admin_override", "Admin override access"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AdminAccessToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "path_prefix",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional: restrict access to files under this path",
                        max_length=1024,
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        help_text="Required justification for the access request"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When this access token expires"),
                ),
                (
                    "is_revoked",
                    models.BooleanField(
                        default=False, help_text="Whether this token has been revoked"
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        help_text="Admin account who requested access",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_access_tokens",
                        to="accounts.account",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        help_text="User whose files will be accessed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_tokens_received",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Access Token",
                "verbose_name_plural": "Admin Access Tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["admin", "-created_at"],
                        name="storage_adm_admin_i_4a959e_idx",
                    ),
                    models.Index(
                        fields=["target_user", "-created_at"],
                        name="storage_adm_target__b6c574_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="storage_adm_expires_c708e7_idx"
                    ),
                ],
            },
        ),
    ]
