# Generated by Django 5.2.9 on 2025-12-11 13:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_add_encryption_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_path', models.CharField(editable=False, help_text='Auto-populated from stored_file.path', max_length=1024)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('custom_slug', models.CharField(blank=True, db_index=True, help_text='Custom URL slug (alphanumeric and hyphens, 3-64 chars)', max_length=64, null=True, unique=True)),
                ('password_hash', models.CharField(blank=True, help_text='Hashed password for protected links', max_length=128, null=True)),
                ('expiry_days', models.IntegerField(choices=[(1, '1 day'), (3, '3 days'), (7, '7 days'), (30, '30 days'), (90, '90 days'), (0, 'Never')], default=7, help_text='Number of days until link expires (0 = never)')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Calculated expiration timestamp', null=True)),
                ('allow_download', models.BooleanField(default=True, help_text='Allow file download (for future read-only links)')),
                ('view_count', models.PositiveIntegerField(default=0, help_text="Number of times this link's info was viewed")),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Number of times the file was downloaded')),
                ('last_accessed_at', models.DateTimeField(blank=True, help_text='Last time this link was viewed or downloaded', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this link is active (false = revoked)')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to=settings.AUTH_USER_MODEL)),
                ('stored_file', models.ForeignKey(help_text='The file being shared', on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='storage.storedfile')),
            ],
            options={
                'verbose_name': 'Share Link',
                'verbose_name_plural': 'Share Links',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'stored_file'], name='storage_sha_owner_i_f8dcab_idx'), models.Index(fields=['expires_at'], name='storage_sha_expires_8aacd1_idx'), models.Index(fields=['is_active'], name='storage_sha_is_acti_e0e6b3_idx')],
            },
        ),
    ]
