# Generated by Django 5.2.9 on 2025-12-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_add_share_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='sort_position',
            field=models.IntegerField(blank=True, db_index=True, help_text='Custom sort position (lower = first, null = alphabetical)', null=True),
        ),
    ]
