# Generated by Django 6.0 on 2026-01-03 20:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_add_sort_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_admin_action', models.BooleanField(db_index=True, default=False, help_text="True if admin acted on another user's files")),
                ('action', models.CharField(choices=[('list', 'List directory'), ('upload', 'Upload file'), ('download', 'Download file'), ('delete', 'Delete file'), ('move', 'Move file'), ('copy', 'Copy file'), ('edit', 'Edit content'), ('preview', 'Preview content'), ('create_dir', 'Create directory'), ('bulk_delete', 'Bulk delete'), ('bulk_move', 'Bulk move'), ('bulk_copy', 'Bulk copy')], db_index=True, max_length=20)),
                ('path', models.CharField(help_text='Primary path affected', max_length=1024)),
                ('destination_path', models.CharField(blank=True, help_text='Destination path for move/copy operations', max_length=1024, null=True)),
                ('paths_affected', models.JSONField(blank=True, help_text='List of paths for bulk operations', null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('performed_by', models.ForeignKey(help_text='User who performed the action (admin for admin actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(help_text='User whose files were affected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File Audit Log',
                'verbose_name_plural': 'File Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['performed_by', '-created_at'], name='storage_fil_perform_643e24_idx'), models.Index(fields=['target_user', '-created_at'], name='storage_fil_target__a17774_idx'), models.Index(fields=['action', '-created_at'], name='storage_fil_action_5068c7_idx'), models.Index(fields=['-created_at'], name='storage_fil_created_3691ed_idx')],
            },
        ),
    ]
