# Generated by Django 6.0 on 2026-01-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_add_file_audit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='encrypted_size',
            field=models.BigIntegerField(blank=True, help_text='Size on disk including encryption overhead (ADR 010)', null=True),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='encryption_method',
            field=models.CharField(choices=[('none', 'No encryption'), ('server', 'Server-side (master key)'), ('server-user', 'Server-side (per-user key)'), ('client', 'Client-side (user holds key)')], default='none', help_text='Encryption method used for this file', max_length=20),
        ),
    ]
