# Generated by Django 6.0 on 2026-01-07 12:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageFileMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_path', models.CharField(db_index=True, help_text="URL path of the page (e.g., '/about/')", max_length=500)),
                ('file_path', models.CharField(db_index=True, help_text="Path to content file (e.g., 'pages/about.md')", max_length=500)),
                ('first_seen', models.DateTimeField(auto_now_add=True, help_text='When this mapping was first reported')),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='When this mapping was last reported')),
                ('owner', models.ForeignKey(help_text='User who owns this content (identified by API key)', on_delete=django.db.models.deletion.CASCADE, related_name='page_file_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page File Mapping',
                'verbose_name_plural': 'Page File Mappings',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['owner', 'page_path'], name='cms_pagefil_owner_i_304048_idx'), models.Index(fields=['owner', 'file_path'], name='cms_pagefil_owner_i_08df90_idx'), models.Index(fields=['last_seen'], name='cms_pagefil_last_se_8464de_idx')],
                'unique_together': {('owner', 'page_path', 'file_path')},
            },
        ),
    ]
