# Generated by Django 6.0 on 2026-01-07 16:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_pagefilemapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_path', models.CharField(db_index=True, help_text="URL path of the page (e.g., '/about/')", max_length=500)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times this page has been viewed')),
                ('first_viewed', models.DateTimeField(auto_now_add=True, help_text='When this page was first viewed')),
                ('last_viewed', models.DateTimeField(auto_now=True, help_text='When this page was last viewed')),
                ('owner', models.ForeignKey(help_text='User who owns this page (identified by API key)', on_delete=django.db.models.deletion.CASCADE, related_name='page_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page Stats',
                'verbose_name_plural': 'Page Stats',
                'ordering': ['-view_count'],
                'indexes': [models.Index(fields=['owner', 'page_path'], name='cms_pagesta_owner_i_5e9d94_idx')],
                'unique_together': {('owner', 'page_path')},
            },
        ),
    ]
