# Generated by Django 6.0 on 2026-01-09 18:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_pagestats'),
        ('storage', '0006_add_encrypted_size_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flag_type', models.CharField(choices=[('ai_generated', 'AI Generated'), ('user_approved', 'User Approved')], help_text='Type of flag (ai_generated, user_approved, etc.)', max_length=50)),
                ('is_active', models.BooleanField(default=False, help_text='Whether this flag is currently active')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Type-specific metadata (schema varies by flag_type)')),
                ('changed_at', models.DateTimeField(auto_now=True, help_text='When this flag was last changed')),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who last changed this flag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flag_changes', to=settings.AUTH_USER_MODEL)),
                ('stored_file', models.ForeignKey(help_text='The file being flagged', on_delete=django.db.models.deletion.CASCADE, related_name='content_flags', to='storage.storedfile')),
            ],
            options={
                'verbose_name': 'Content Flag',
                'verbose_name_plural': 'Content Flags',
            },
        ),
        migrations.CreateModel(
            name='ContentFlagHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('was_active', models.BooleanField(help_text='Previous is_active state')),
                ('is_active', models.BooleanField(help_text='New is_active state')),
                ('metadata', models.JSONField(default=dict, help_text='Metadata snapshot at time of change')),
                ('changed_at', models.DateTimeField(auto_now_add=True, help_text='When this change occurred')),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who made this change', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('flag', models.ForeignKey(help_text='The flag that was changed', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='cms.contentflag')),
            ],
            options={
                'verbose_name': 'Content Flag History',
                'verbose_name_plural': 'Content Flag History',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contentflag',
            index=models.Index(fields=['stored_file', 'flag_type'], name='cms_content_stored__2dc5fb_idx'),
        ),
        migrations.AddIndex(
            model_name='contentflag',
            index=models.Index(fields=['flag_type', 'is_active'], name='cms_content_flag_ty_aa38bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentflag',
            unique_together={('stored_file', 'flag_type')},
        ),
    ]
