# Generated by Django 6.0 on 2026-01-15 17:34

import accounts.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(default=accounts.models.generate_platform_invite_key, max_length=64, unique=True)),
                ('email', models.EmailField(help_text='Email address that must be used to claim this invite.', max_length=254)),
                ('name', models.CharField(help_text="Descriptive name, e.g., 'Acme Corp Onboarding'", max_length=255)),
                ('is_used', models.BooleanField(default=False, help_text='Whether this invite has been claimed.')),
                ('used_at', models.DateTimeField(blank=True, help_text='When the invite was claimed.', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Invite expires after this time. Null = never expires.', null=True)),
                ('quota_bytes', models.BigIntegerField(default=0, help_text='Storage quota for the new org in bytes. 0 = unlimited.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Platform admin who created this invite.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_platform_invites', to='accounts.account')),
                ('used_by', models.ForeignKey(blank=True, help_text='Account that claimed this invite.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_platform_invite', to='accounts.account')),
            ],
            options={
                'verbose_name': 'Platform Invite',
                'verbose_name_plural': 'Platform Invites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key'], name='accounts_pl_key_9030f3_idx'), models.Index(fields=['email'], name='accounts_pl_email_fbc6da_idx'), models.Index(fields=['is_active', 'is_used'], name='accounts_pl_is_acti_c8cafc_idx')],
            },
        ),
    ]
