# Generated by Django 5.2.9 on 2025-12-05 17:00

from django.db import migrations


def create_profiles(apps, schema_editor):
    """Create UserProfile for all existing users."""
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('accounts', 'UserProfile')

    for user in User.objects.all():
        UserProfile.objects.get_or_create(
            user=user,
            defaults={
                'is_email_verified': user.is_superuser  # Admins start verified
            }
        )


def remove_profiles(apps, schema_editor):
    """Reverse migration - delete all profiles."""
    UserProfile = apps.get_model('accounts', 'UserProfile')
    UserProfile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_apikey_revoked_at_apikey_scope_userprofile_and_more'),
    ]

    operations = [
        migrations.RunPython(create_profiles, remove_profiles),
    ]
