# Generated by Django 5.2.9 on 2025-12-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20251205_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='storage_quota_bytes',
            field=models.BigIntegerField(default=0, help_text='Maximum storage allowed in bytes. 0 = unlimited.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='storage_used_bytes',
            field=models.BigIntegerField(default=0, help_text='Current storage usage in bytes.'),
        ),
    ]
