# Generated by Django 6.0 on 2026-01-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_add_invite_tracking_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="show_email_to_org",
            field=models.BooleanField(
                default=True, help_text="Show email to other org members."
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="show_name_to_org",
            field=models.BooleanField(
                default=True, help_text="Show name to other org members."
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="default_show_email_to_org",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="default_show_name_to_org",
            field=models.BooleanField(default=True),
        ),
    ]
