# Generated by Django 6.0 on 2026-01-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_storage_quota_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_create_shares',
            field=models.BooleanField(default=True, help_text='User can create share links.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_delete',
            field=models.BooleanField(default=True, help_text='User can delete files and folders.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_move',
            field=models.BooleanField(default=True, help_text='User can move/rename files and folders.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_overwrite',
            field=models.BooleanField(default=True, help_text='User can overwrite/edit existing files.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_upload',
            field=models.BooleanField(default=True, help_text='User can upload new files.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_share_links',
            field=models.PositiveIntegerField(default=0, help_text='Maximum active share links allowed. 0 = unlimited.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_upload_bytes',
            field=models.BigIntegerField(default=0, help_text='Per-file upload size limit in bytes. 0 = use server default.'),
        ),
    ]
