# Generated by Django 6.0 on 2026-01-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_permission_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='webhook_enabled',
            field=models.BooleanField(default=False, help_text='Whether webhook notifications are active.'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='webhook_last_status',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], help_text='Status of last webhook delivery.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='webhook_last_triggered',
            field=models.DateTimeField(blank=True, help_text='Last time webhook was triggered.', null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='webhook_secret',
            field=models.CharField(blank=True, help_text='HMAC secret for signing webhook payloads. Auto-generated.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='URL to POST when content changes. Leave blank to disable.', max_length=500, null=True),
        ),
    ]
