"""
Django settings for _core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&oce!2!vbhefu^t%3&64&+pu-^wtm-0mcr(@d&uwx%nc3ub*=p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'corsheaders',
    'core',
    'accounts',
    'storage',
    'cms',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = '_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.authentication.APIKeyAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# drf-spectacular configuration
SPECTACULAR_SETTINGS = {
    'TITLE': 'Storm Cloud API',
    'DESCRIPTION': 'Self-hostable cloud storage with markdown CMS capabilities.',
    'VERSION': '0.1.0',
    'SERVE_INCLUDE_SCHEMA': False,

    # Swagger UI settings
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
        'displayRequestDuration': True,
        'filter': True,
        'deepLinking': True,
    },

    # Security schemes
    'SECURITY': [
        {'BearerAuth': []},
        {'SessionAuth': []},
    ],
    'COMPONENTS': {
        'securitySchemes': {
            'BearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'description': 'API key authentication. Get a key from /api/v1/auth/tokens/',
            },
            'SessionAuth': {
                'type': 'apiKey',
                'in': 'cookie',
                'name': 'sessionid',
                'description': 'Session cookie authentication. Login at /api/v1/auth/login/',
            },
        },
    },

    # Tag organization
    'TAGS': [
        {'name': 'Authentication', 'description': 'Login, registration, and API key management'},
        {'name': 'Files', 'description': 'File and directory operations'},
        {'name': 'CMS', 'description': 'Content management (coming soon)'},
        {'name': 'Administration', 'description': 'Admin-only user and key management'},
    ],
}

# =============================================================================
# STORM CLOUD SETTINGS
# =============================================================================

# Storage
STORMCLOUD_STORAGE_BACKEND = 'core.storage.local.LocalStorageBackend'
STORMCLOUD_STORAGE_ROOT = BASE_DIR / 'storage_root'

# Registration
STORMCLOUD_ALLOW_REGISTRATION = False  # Only admin can create users by default

# Email verification
STORMCLOUD_REQUIRE_EMAIL_VERIFICATION = True  # Admins bypass this
STORMCLOUD_EMAIL_VERIFICATION_EXPIRY_HOURS = 24

# Email verification link format
# None = direct API link (/api/v1/auth/verify-email/?token=xxx)
# String = custom URL template, use {token} placeholder
# Example: "https://myapp.com/verify?token={token}"
STORMCLOUD_EMAIL_VERIFICATION_LINK = None

# API keys
STORMCLOUD_MAX_API_KEYS_PER_USER = 0  # 0 = unlimited

# CORS
STORMCLOUD_CORS_ORIGINS = []  # List of allowed origins, empty = none allowed
# Example: ["https://myapp.com", "http://localhost:3000"]

# Email templates (can be overridden)
STORMCLOUD_EMAIL_VERIFICATION_SUBJECT = "Verify your Storm Cloud account"
STORMCLOUD_EMAIL_VERIFICATION_BODY = """
Hello {username},

Please verify your email address by clicking the link below:

{verification_link}

This link expires in {expiry_hours} hours.

If you did not create an account, please ignore this email.

- Storm Cloud
"""

# =============================================================================
# EMAIL CONFIGURATION
# =============================================================================
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@stormcloud.local'

# =============================================================================
# CORS HEADERS
# =============================================================================
CORS_ALLOWED_ORIGINS = STORMCLOUD_CORS_ORIGINS
CORS_ALLOW_CREDENTIALS = True  # Required for session auth

# =============================================================================
# LOGGING - Security Events
# =============================================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'security': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'security_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'security.log',
            'formatter': 'security',
        },
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'stormcloud.security': {
            'handlers': ['security_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
