"""
Django settings for _core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-&oce!2!vbhefu^t%3&64&+pu-^wtm-0mcr(@d&uwx%nc3ub*=p')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG and ALLOWED_HOSTS are set in dev.py and production.py


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'django_mercury',
    'django_spellbook',
    'corsheaders',
    'core',
    'accounts',
    'storage',
    'cms',
    'docs_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'core.middleware.SentryContextMiddleware',  # Add user context to Sentry errors
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = '_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / '_core' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Default SQLite for local development
# Overridden in dev.py and production.py

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.authentication.APIKeyAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'login': config('THROTTLE_LOGIN_RATE', default='5/min'),
        'auth': config('THROTTLE_AUTH_RATE', default='10/hour'),
        'uploads': config('THROTTLE_UPLOAD_RATE', default='100/hour'),
        'downloads': config('THROTTLE_DOWNLOAD_RATE', default='500/hour'),
        'user': config('THROTTLE_USER_RATE', default='1000/hour'),
        'anon_login': config('THROTTLE_ANON_LOGIN_RATE', default='10/hour'),
        'anon_registration': config('THROTTLE_ANON_REGISTRATION_RATE', default='5/hour'),
        'public_share': config('THROTTLE_PUBLIC_SHARE_RATE', default='60/min'),
        'public_share_download': config('THROTTLE_PUBLIC_SHARE_DOWNLOAD_RATE', default='30/min'),
    },
}

# drf-spectacular configuration
SPECTACULAR_SETTINGS = {
    'TITLE': 'Storm Cloud API',
    'DESCRIPTION': 'Self-hostable cloud storage with markdown CMS capabilities.',
    'VERSION': '0.1.0',
    'SERVE_INCLUDE_SCHEMA': False,

    # Swagger UI settings
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
        'displayRequestDuration': True,
        'filter': True,
        'deepLinking': True,
    },

    # Security schemes
    'SECURITY': [
        {'BearerAuth': []},
        {'SessionAuth': []},
    ],
    'COMPONENTS': {
        'securitySchemes': {
            'BearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'description': 'API key authentication. Get a key from /api/v1/auth/tokens/',
            },
            'SessionAuth': {
                'type': 'apiKey',
                'in': 'cookie',
                'name': 'sessionid',
                'description': 'Session cookie authentication. Login at /api/v1/auth/login/',
            },
        },
    },

    # Tag organization
    'TAGS': [
        {'name': 'Authentication', 'description': 'Login, registration, and API key management'},
        {'name': 'Files', 'description': 'File and directory operations'},
        {'name': 'CMS', 'description': 'Content management (coming soon)'},
        {'name': 'Administration', 'description': 'Admin-only user and key management'},
    ],
}

# =============================================================================
# STORM CLOUD SETTINGS
# =============================================================================

# Storage
STORMCLOUD_STORAGE_BACKEND = config(
    'STORMCLOUD_STORAGE_BACKEND',
    default='core.storage.local.LocalStorageBackend'
)
STORMCLOUD_STORAGE_ROOT = BASE_DIR / 'storage_root'

# Registration
STORMCLOUD_ALLOW_REGISTRATION = config(
    'STORMCLOUD_ALLOW_REGISTRATION',
    default=False,
    cast=bool
)

# Email verification
STORMCLOUD_REQUIRE_EMAIL_VERIFICATION = config(
    'STORMCLOUD_REQUIRE_EMAIL_VERIFICATION',
    default=True,
    cast=bool
)
STORMCLOUD_EMAIL_VERIFICATION_EXPIRY_HOURS = config(
    'STORMCLOUD_EMAIL_VERIFICATION_EXPIRY_HOURS',
    default=24,
    cast=int
)

# Email verification link format
# None = direct API link (/api/v1/auth/verify-email/?token=xxx)
# String = custom URL template, use {token} placeholder
# Example: "https://myapp.com/verify?token={token}"
STORMCLOUD_EMAIL_VERIFICATION_LINK = None

# API keys
STORMCLOUD_MAX_API_KEYS_PER_USER = config(
    'STORMCLOUD_MAX_API_KEYS_PER_USER',
    default=0,
    cast=int
)

# Share Links
STORMCLOUD_ALLOW_UNLIMITED_SHARE_LINKS = config(
    'STORMCLOUD_ALLOW_UNLIMITED_SHARE_LINKS',
    default=True,
    cast=bool
)
STORMCLOUD_DEFAULT_SHARE_EXPIRY_DAYS = config(
    'STORMCLOUD_DEFAULT_SHARE_EXPIRY_DAYS',
    default=7,
    cast=int
)

# CORS
STORMCLOUD_CORS_ORIGINS = config(
    'STORMCLOUD_CORS_ORIGINS',
    default='',
    cast=Csv()
)

# Email templates (can be overridden)
STORMCLOUD_EMAIL_VERIFICATION_SUBJECT = "Verify your Storm Cloud account"
STORMCLOUD_EMAIL_VERIFICATION_BODY = """
Hello {username},

Please verify your email address by clicking the link below:

{verification_link}

This link expires in {expiry_hours} hours.

If you did not create an account, please ignore this email.

- Storm Cloud
"""

# =============================================================================
# EMAIL CONFIGURATION
# =============================================================================
EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend'
)
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@stormcloud.local')

# =============================================================================
# CORS HEADERS
# =============================================================================
CORS_ALLOWED_ORIGINS = STORMCLOUD_CORS_ORIGINS
CORS_ALLOW_CREDENTIALS = True  # Required for session auth

# =============================================================================
# DJANGO SPELLBOOK SETTINGS
# =============================================================================
SPELLBOOK_MD_APP = [
    'docs_app',
]

SPELLBOOK_MD_PATH = [
    'docs_content',
]

SPELLBOOK_MD_URL_PREFIX = [
    'docs',
]